name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make build
      run: |
              sudo apt-get update
              sudo apt install googletest make cmake build-essential
              pushd; cd /usr/src/googletest; cmake CMakeLists.txt; make; sudo make install; popd
              make build
    - name: make starter tests
      run: make starter-tests
    - name: make main tests
      run: make base-tests
