name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make build
      run: |
              sudo apt-get update >> /dev/null 2>&1
              sudo apt install googletest make cmake build-essential
              pushd .; cd /usr/src/googletest; sudo cmake CMakeLists.txt; sudo make; sudo make install; popd
              make build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make starter tests
      run: |
              sudo apt-get update >> /dev/null 2>&1
              sudo apt install googletest make cmake build-essential
              pushd .; cd /usr/src/googletest; sudo cmake CMakeLists.txt; sudo make; sudo make install; popd
              make starter-tests
    - name: make main tests
      run: make base-tests

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy image
       run: echo "We'd build & deploy our image here"
