name: Python Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
              cd python
              make build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: |
              cd python
              apt install flake8
              make lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test setup
      run: |
              cd python
              echo "Testing python here"
    - name: main tests
      run: |
              cd python
              make test

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy image
      run: |
              cd python
              echo "We'd build & deploy our image here"
